# Generated by Django 3.1.3 on 2020-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201124_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='name',
            field=models.CharField(default='harry', max_length=40),
            preserve_default=False,
        ),
    ]
