# Generated by Django 3.1.3 on 2020-11-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201125_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
    ]
