# Generated by Django 3.1.3 on 2020-11-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_bids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
