# Generated by Django 3.1.3 on 2020-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_num_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
